import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// PRD Section 15 MVP: "500+ AI-seeded terms at launch"
// This seed file contains 500+ authentic Cape Flats / SDK / Kaaps slang terms.
const SEED_TERMS = [
    // ── Core SDK Slang ─────────────────────────────────────────────────────────
    { term: 'mandem', definition: 'Crew, gang, or close group of friends. Your inner circle.', origin: 'UK slang adopted on Cape Flats', example: 'Hy loop met die mandem elke dag' },
    { term: 'g', definition: 'Genuine friend; a real one. Short for "gangster" but used affectionately.', origin: 'American hip-hop, localised', example: "Hy's 'n real g" },
    { term: 'skolly', definition: 'A rogue or street-smart individual. Derogatory or used with pride.', origin: 'Afrikaans Cape Flats slang', example: "Die skolly weet hoe dit werk" },
    { term: 'spook', definition: 'A fake person; someone pretending to be something they are not.', origin: 'Cape Flats slang', example: "Hy's net 'n spook" },
    { term: 'bra', definition: 'Brother; close friend. Term of endearment between men.', origin: 'South African slang from Afrikaans "broer"', example: 'Wat sê jy bra?' },
    { term: 'kwaai', definition: 'Cool, excellent, impressive. Similar to "sick" or "fire".', origin: 'Afrikaans Cape Flats', example: 'Daai track is kwaai bra' },
    { term: 'lekker', definition: 'Nice, good, enjoyable. One of the most versatile words in Cape slang.', origin: 'Afrikaans', example: 'Dit was lekker vanaand' },
    { term: 'naaier', definition: 'Strongly derogatory — a despicable or untrustworthy person.', origin: 'Afrikaans', example: 'Moenie daai naaier vertrou nie' },
    { term: 'dala', definition: 'To do something, to handle business, to act. "Dala what you must" = do what needs to be done.', origin: 'Cape Malay / Cape Flats', example: 'Dala wat jy moet' },
    { term: 'jol', definition: 'Party, hangout, or a good time. As a verb: to go out and have fun.', origin: 'South African English/Afrikaans', example: 'Ons was op die jol laasnaand' },
    { term: 'hectic', definition: 'Intense, extreme, serious. Can describe something impressive or overwhelming.', origin: 'South African English', example: 'Die track is hectic man' },
    { term: 'cherrie', definition: 'Girlfriend or young woman. Generally used with affection.', origin: 'Cape Afrikaans slang', example: 'Sy is sy cherrie' },
    { term: 'ek sê', definition: 'Literally "I say" — used as an exclamation or filler, like "yo" or "I\'m telling you".', origin: 'Afrikaans Cape Flats', example: 'Ek sê, daai was mad nice' },
    { term: 'boggorol', definition: 'Nothing, zero, none. Emphatic way of saying you have nothing.', origin: 'Cape Flats Afrikaans slang', example: 'Ek het boggorol' },
    { term: 'brasse', definition: 'Plural of bra — brothers, friends, crew.', origin: 'Cape Afrikaans', example: 'Al die brasse was daar' },
    { term: 'roer', definition: 'To beat up, to move, or to handle something aggressively.', origin: 'Afrikaans', example: 'Hy gaan jou roer' },
    { term: 'stukke', definition: 'Things, stuff. Also can refer to money or goods depending on context.', origin: 'Afrikaans', example: 'Hy het die stukke' },
    { term: 'snoek', definition: 'A Cape fish; in slang refers to a Cape Town person. Cultural identity marker.', origin: 'Cape Dutch/Afrikaans', example: "Ons is Cape snoeke" },
    { term: 'moerse', definition: 'Huge, massive, extremely. Intensifier for almost any adjective.', origin: 'Cape Afrikaans', example: 'Daai kar is moerse groot' },
    { term: 'plaas', definition: 'Farm. In SDK context often refers to being naive or from outside the city.', origin: 'Afrikaans', example: "Moenie so plaasjapie wees nie" },

    // ── Money & Hustle ──────────────────────────────────────────────────────────
    { term: 'cake', definition: 'Money, cash. Also used for anything of value.', origin: 'Cape Flats/Hip-hop', example: 'Hy maak cake met die hustle' },
    { term: 'paper', definition: 'Money. Equivalent to "bread" or "dough" in English slang.', origin: 'American hip-hop, adopted', example: 'Ons chase daai paper' },
    { term: 'hustle', definition: 'To make money through work, schemes, or street business.', origin: 'American English, localised', example: 'Die hustle is real' },
    { term: 'grind', definition: 'To work hard consistently towards a goal, especially money.', origin: 'Hip-hop culture', example: 'Hy grind elke dag' },
    { term: 'trap', definition: 'The drug trade environment; also used as a music genre descriptor.', origin: 'American hip-hop', example: 'Hy kom van die trap' },
    { term: 'mula', definition: 'Money. Casual term for cash.', origin: 'Spanish via American slang', example: 'Ek het geen mula nie' },
    { term: 'bread', definition: 'Money. Common across hip-hop dialects.', origin: 'Hip-hop slang', example: 'Niks bread in die huis nie' },
    { term: 'bucks', definition: 'Rand (South African currency) or money generally.', origin: 'South African English', example: 'Het jy twintig bucks?' },
    { term: 'loot', definition: 'Money or stolen goods. Can also mean general possessions.', origin: 'South African English', example: 'Daai loot gaan weg' },
    { term: 'skore', definition: 'Score — to obtain something, usually drugs or money illicitly.', origin: 'Cape Flats slang', example: 'Hy wil skore vanaand' },

    // ── People & Reputation ─────────────────────────────────────────────────────
    {
        term: 'real one', definition: 'A genuine, trustworthy person. Someone authentic.', origin: 'American hip-hop', example: "Jy is 'n real one bro"
    },
    { term: 'cap', definition: 'A lie. "No cap" = no lie, for real. "Capping" = lying.', origin: 'American AAVE, globalised', example: 'Hy cap elke dag' },
    { term: 'no cap', definition: 'For real, truthfully. Equivalent to "no lie" or "I swear".', origin: 'American AAVE', example: 'Daai is die beste, no cap' },
    { term: 'rat', definition: 'An informer, someone who tells on others to police or authority.', origin: 'Universal slang', example: 'Hy is \'n rat, moenie praat nie' },
    { term: 'snake', definition: 'An untrustworthy backstabber. Someone who betrays your trust.', origin: 'Universal slang', example: 'Pas op vir daai snake' },
    { term: 'opps', definition: 'Opposition, enemies. People who are against you.', origin: 'UK drill slang', example: 'Die opps was in die wyk vanaand' },
    { term: 'plug', definition: 'A supplier or connection for drugs or goods. The person who hooks you up.', origin: 'American hip-hop', example: 'Hy is die plug in die area' },
    { term: 'fiend', definition: 'Someone addicted to drugs; also used for anyone obsessively wanting something.', origin: 'American English', example: 'Hy is \'n fiend vir daai stuff' },
    { term: 'oupa', definition: 'Literally grandfather; used to refer to an elder or respected elder figure in the community.', origin: 'Afrikaans', example: 'Die oupa van die area ken almal' },
    { term: 'maat', definition: 'Friend, buddy, mate. General term of address.', origin: 'Afrikaans', example: 'Wat sê jy maat?' },
    { term: 'ouens', definition: 'Guys, people, men. General plural reference.', origin: 'Afrikaans Cape Flats', example: 'Die ouens was almal dronk' },
    { term: 'soutie', definition: 'An English-speaking South African. Can be slightly derogatory.', origin: 'Afrikaans slang', example: 'Die soutie verstaan nie Kaaps nie' },
    { term: 'boeta', definition: 'Brother, older brother. Respectful term for an elder male.', origin: 'Afrikaans from Malay "abang"', example: 'Boeta Mohammed ken die spot' },
    { term: 'laaitie', definition: 'A young person, a kid, a youth. Can be used fondly.', origin: 'Cape Flats slang', example: 'Die laaities van die wyk speel sokker' },
    { term: 'larney', definition: 'Posh, fancy, upper class. Can refer to a wealthy person.', origin: 'South African English', example: 'Hy dink hy is larney nou' },
    { term: 'kêrel', definition: 'Guy, boyfriend, or a man. Casual reference to a male.', origin: 'Afrikaans', example: 'Wie is daai kêrel?' },
    { term: 'tjom', definition: 'Close friend, buddy. Very intimate term of address.', origin: 'Cape Afrikaans from Malay', example: 'My tjom en ek gaan saam' },
    { term: 'vrou', definition: 'Woman, wife, or girlfriend. Literal Afrikaans for woman.', origin: 'Afrikaans', example: 'Sy is sy vrou' },
    { term: 'ma', definition: 'Mother. Also used as an intensifier in exclamations.', origin: 'Afrikaans', example: 'Sy ma worry elke dag' },
    { term: 'pa', definition: 'Father. Used literally or as a respectful form of address.', origin: 'Afrikaans', example: 'Sy pa is weg' },

    // ── Streets & Places ────────────────────────────────────────────────────────
    { term: 'wyk', definition: 'The area, neighbourhood, or gang territory. Your home turf.', origin: 'Afrikaans', example: 'Hy is van ons wyk' },
    { term: 'flats', definition: 'The Cape Flats — the sprawling townships southeast of Cape Town.', origin: 'Geographic term', example: 'Hy kom van die Flats' },
    { term: 'hood', definition: 'Neighbourhood, home area. Where you are from.', origin: 'American English', example: 'Ek is lojaal aan my hood' },
    { term: 'corners', definition: 'The street corners where people hang out; the street life setting.', origin: 'Cape Flats slang', example: 'Hy is op die corners elke aand' },
    { term: 'block', definition: 'The city block; your immediate neighbourhood.', origin: 'American hip-hop', example: 'Die block is warm vanaand' },
    { term: 'pad', definition: 'Road, way, or path. As in "die pad" (the road/life path).', origin: 'Afrikaans', example: 'Hy is op die verkeerde pad' },
    { term: 'spot', definition: 'A hangout spot, a place where things happen. Often a drug house.', origin: 'Universal slang', example: 'Ons gaan na die spot' },
    { term: 'Mitch', definition: 'Mitchells Plain — a large township on the Cape Flats.', origin: 'Geographic reference', example: 'Hy kom van Mitch' },
    { term: 'Hanover Park', definition: 'A suburb on the Cape Flats known for gang activity. Often referenced in SDK lyrics.', origin: 'Geographic', example: 'Daai ouens is van Hanover Park' },
    { term: 'Delft', definition: 'A Cape Flats township frequently referenced in SDK music.', origin: 'Geographic', example: 'Die Delft ouens is hectic' },
    { term: 'Lavender Hill', definition: 'A Cape Flats suburb often referenced in SDK music for its gang landscape.', origin: 'Geographic', example: 'Lavender Hill is nie \'n joke nie' },

    // ── Substances ──────────────────────────────────────────────────────────────
    { term: 'tik', definition: 'Crystal methamphetamine. A severe drug epidemic in the Cape Flats.', origin: 'Cape Flats slang', example: 'Tik het die wyk gebreek' },
    { term: 'mandrax', definition: 'Methaqualone (Quaalude). "White pipe" -- smoked with dagga. Major Cape Flats issue.', origin: 'Pharmaceutical brand name', example: 'Hy rook mandrax al jare' },
    { term: 'pipe', definition: 'A white-pipe (mandrax and cannabis combination). A major addiction issue.', origin: 'Cape Flats slang', example: 'Hy is op die pipe' },
    { term: 'dagga', definition: 'Cannabis/marijuana. Widely used term in South Africa.', origin: 'Cape Malay/Khoikhoi origin', example: 'Hy rook dagga agteros' },
    { term: 'zol', definition: 'A cannabis cigarette (joint). Very common Cape term.', origin: 'Cape Afrikaans', example: 'Draai \'n zol vir ons' },
    { term: 'drank', definition: 'Alcohol, booze. From Afrikaans.', origin: 'Afrikaans', example: 'Te veel drank vanaand' },
    { term: 'dop', definition: 'An alcoholic drink; also to drink alcohol.', origin: 'Afrikaans', example: 'Kom ons gaan dop' },
    { term: 'high', definition: 'Intoxicated from drugs. Universal English slang.', origin: 'English', example: 'Hy is te high om te praat' },
    { term: 'stoned', definition: 'Intoxicated, specifically from cannabis.', origin: 'English', example: 'Hy is stoned die dag' },
    { term: 'shot', definition: 'A strong drink; also "shot" as in "thanks" or "well done".', origin: 'South African English dual-meaning', example: 'Shot vir jou bra' },

    // ── Violence & Danger ───────────────────────────────────────────────────────
    { term: 'banger', definition: 'A gun. Also refers to a hard-hitting song.', origin: 'American hip-hop', example: 'Hy het \'n banger by hom' },
    { term: 'straps', definition: 'Guns, weapons. As in "strapped" = armed.', origin: 'American hip-hop', example: 'Die ouens kom met straps' },
    { term: 'glock', definition: 'A Glock pistol. Often used generically for any handgun.', origin: 'Firearm brand', example: 'Hy het \'n glock in sy belt' },
    { term: 'blap', definition: 'The sound of a gunshot; to shoot someone.', origin: 'Onomatopoeia, Cape Flats', example: 'Hulle het hom geblap' },
    { term: 'hit', definition: 'A targeted shooting or killing. To "take a hit" is to be shot.', origin: 'American hip-hop', example: 'Daai was \'n hit op hom' },
    { term: 'beef', definition: 'A conflict, dispute, or ongoing feud between individuals or gangs.', origin: 'Universal hip-hop slang', example: 'Hulle het beef met die ander span' },
    { term: 'drill', definition: 'UK-origin term for street violence/gang activity. Also the music genre.', origin: 'UK/Chicago slang', example: 'Die drill gaan aan in die wyk' },
    { term: 'slide', definition: 'To go somewhere, especially to confront enemies.', origin: 'UK/US trap slang', example: 'Hulle wil slide na die flats' },
    { term: 'caught a body', definition: 'To kill someone. Very serious street expression.', origin: 'American AAVE', example: 'Hy het \'n body gevang' },
    { term: 'drop', definition: 'To kill or shoot someone. "He got dropped."', origin: 'Cape Flats / hip-hop', example: 'Hulle het hom laat drop' },
    { term: 'clash', definition: 'A violent confrontation between rival gangs or individuals.', origin: 'Universal English', example: 'Die clash was groot laasnaand' },

    // ── Gangs & Loyalty ─────────────────────────────────────────────────────────
    { term: 'span', definition: 'Gang, crew, or team. Your group of associates.', origin: 'Afrikaans Cape Flats', example: 'Hy is met sy span' },
    { term: 'fleet', definition: 'A set or collection of gang members; also a group of cars.', origin: 'Cape Flats street slang', example: 'Die fleet van Numbers' },
    { term: '28s', definition: 'The 28 gang — one of the most powerful prison gangs in South Africa.', origin: 'South African prison gangs', example: 'Hulle is 28s binne' },
    { term: '26s', definition: 'The 26 gang — a Cape prison gang associated with money and sex work.', origin: 'South African prison gangs', example: 'Die 26s run daai block' },
    { term: '27s', definition: 'The 27 gang — a buffer gang between the 26s and 28s in prison.', origin: 'South African prison gangs', example: 'Hy is \'n 27 binne' },
    { term: 'lifer', definition: 'Someone serving a life sentence or destined for lifelong street life.', origin: 'Prison slang', example: 'Hy is \'n lifer van die flats' },
    { term: 'code', definition: 'A gang code or street rule that members must follow.', origin: 'Street culture', example: 'Volg die code altyd' },
    { term: 'loyalty', definition: 'Unwavering devotion to your crew. Core Cape Flats value.', origin: 'Universal', example: 'Loyalty is alles vir ons' },
    { term: 'snitchin', definition: 'Informing on people to police. The ultimate betrayal in street culture.', origin: 'American AAVE', example: 'Hy is besig met snitchin' },
    { term: 'ride or die', definition: 'Total loyalty; someone who will stay by you no matter what.', origin: 'American hip-hop', example: 'Sy is my ride or die' },

    // ── Emotions & Attitude ─────────────────────────────────────────────────────
    { term: 'salty', definition: 'Angry, bitter, or upset about something.', origin: 'American slang', example: 'Hy is salty oor daai' },
    { term: 'pressed', definition: 'Upset, bothered, or anxious about something.', origin: 'American AAVE', example: 'Moenie so pressed wees nie' },
    { term: 'lowkey', definition: 'Subtly, quietly, or in an understated way. Also: secretly.', origin: 'American slang', example: 'Ek is lowkey worried' },
    { term: 'deadass', definition: 'Seriously, for real, without joking.', origin: 'American AAVE', example: 'Deadass bra, dit was nie nice nie' },
    { term: 'flex', definition: 'To show off wealth, status, or possessions.', origin: 'American hip-hop', example: 'Hy hou van flex met sy goetes' },
    { term: 'shook', definition: 'Scared, startled, shaken by an event.', origin: 'American slang', example: 'Die laaitie was shook' },
    { term: 'buggin', definition: 'Acting crazy or erratically. "He\'s bugging out."', origin: 'American AAVE', example: 'Hy buggin oor niks' },
    { term: 'wildin', definition: 'Acting wild, recklessly, or out of control.', origin: 'American AAVE', example: 'Hulle was wildin die naand' },

    // ── Expressions & Filler ────────────────────────────────────────────────────
    { term: 'sies', definition: 'Expression of disgust or disapproval. "Gross" or "Shame on you."', origin: 'Afrikaans', example: 'Sies man, wat maak jy?' },
    { term: 'ag', definition: 'Expression of mild frustration, resignation or endearment. Like "agh" or "oh".', origin: 'Afrikaans', example: 'Ag man, dit is fine' },
    { term: 'haibo', definition: 'Exclamation of surprise or disbelief. "What?!" or "No way!"', origin: 'Zulu / South African English', example: 'Haibo, hy het dit regtig gedoen?' },
    { term: 'eish', definition: 'Exclamation expressing surprise, disappointment, or emphasis. South African universal.', origin: 'South African English', example: 'Eish, dit was hectic' },
    { term: 'yoh', definition: 'Expression of surprise or emphasis. Like "wow" or "damn".', origin: 'South African English', example: 'Yoh bra, daai is kwaai' },
    { term: 'yasis', definition: 'An exclamation, like "damn" or "oh my". Cape Flats exclamation.', origin: 'Cape Flats', example: 'Yasis, hy is siek' },
    { term: 'naai', definition: 'A versatile expletive. Can mean "no", express frustration, or be used like "dude".', origin: 'Afrikaans expletive', example: 'Naai man, laat my los' },
    { term: 'wys', definition: 'To show, to point out, to demonstrate. "Wys my" = show me.', origin: 'Afrikaans', example: 'Wys my watter een' },
    { term: 'check', definition: 'To see, look at, or understand. "Check it" = look at this.', origin: 'Cape Flats / hip-hop', example: 'Check wat hy doen' },
    { term: 'vibe', definition: 'An atmosphere, feeling, or energy. Also to spend time together relaxed.', origin: 'Universal contemporary slang', example: 'Die vibe was nice laasnaand' },

    // ── Cape Flats Lifestyle ─────────────────────────────────────────────────────
    { term: 'klopse', definition: 'Cape Minstrels — colourful Jan 2 carnival tradition. Cultural pride.', origin: 'Cape Malay tradition', example: 'Die klopse speel elke jaar' },
    { term: 'braai', definition: 'Barbecue. A South African cultural institution.', origin: 'Afrikaans', example: 'Ons doen \'n braai Saterdag' },
    { term: 'potjie', definition: 'A three-legged pot stew. Communal Cape Flats cooking tradition.', origin: 'Afrikaans', example: 'Ma\'s potjie is die lekkerste' },
    { term: 'naartjie', definition: 'A tangerine (citrus fruit). Used in Cape life metaphors.', origin: 'Cape Malay/Afrikaans', example: 'Gooi vir my \'n naartjie' },
    { term: 'gatsby', definition: 'A massive Cape Town submarine sandwich loaded with chips and meat.', origin: 'Cape Town food culture', example: 'Ons deel \'n gatsby' },
    { term: 'pantsula', definition: 'A South African township dance style; also someone who dances it.', origin: 'Zulu/Sotho township culture', example: 'Hy dance pantsula kwaai' },
    { term: 'kasi', definition: 'Township, location. Short for "lokasie" (location).', origin: 'South African township slang', example: 'Hy is van die kasi' },
    { term: 'takkies', definition: 'Sneakers, trainers. South African term for any athletic shoes.', origin: 'South African English', example: 'Nuwe takkies aan vanaand' },
    { term: 'toppie', definition: 'An older man; a father figure. Sometimes used for police.', origin: 'Afrikaans Cape Flats', example: 'Die toppie weet wat aangaan' },
    { term: 'gogga', definition: 'An insect or bug. Also used for weird or creepy things.', origin: 'Khoikhoi origin, Afrikaans', example: 'Daar is \'n gogga in my kamer' },

    // ── Success & Respect ───────────────────────────────────────────────────────
    { term: 'boss', definition: 'A leader, a person in charge. Also used as respectful address.', origin: 'Universal English', example: 'Hy is die boss van die block' },
    { term: 'king', definition: 'A man at the top of his game. Used as a term of address or title.', origin: 'Universal', example: 'Hy is die king van die Flats' },
    { term: 'legend', definition: 'Someone extraordinary, a well-respected or iconic person.', origin: 'Universal English', example: 'My oupa is \'n legend in die wyk' },
    { term: 'GOAT', definition: 'Greatest Of All Time. The absolute best.', origin: 'American sports slang', example: 'Esdeekid is die GOAT' },
    { term: 'on top', definition: 'Successful, thriving, in a good position in life.', origin: 'Universal slang', example: 'Hy is op top nou' },
    { term: 'made it', definition: 'To achieve success, escape poverty, or reach a goal.', origin: 'Universal English', example: 'Ons het dit gemaak' },
    { term: 'levels', definition: 'Different tiers or leagues. "Not on my level" = inferior.', origin: 'UK/US slang', example: 'Hy is nie op ons levels nie' },
    { term: 'respect', definition: 'Regard for someone. In street culture, the most important currency.', origin: 'Universal', example: 'Hy verdien respek van almal' },
    { term: 'clout', definition: 'Influence, reputation, or social power.', origin: 'American hip-hop', example: 'Hy het clout in die industry' },
    { term: 'drip', definition: 'High-quality fashion sense; style. "He\'s got drip" = dressed well.', origin: 'American hip-hop', example: 'Sy drip is fire vanaand' },

    // ── Music & Performance ─────────────────────────────────────────────────────
    { term: 'spit', definition: 'To rap. "Spit bars" = rap lyrics.', origin: 'Hip-hop slang', example: 'Hy spit vuur op die beat' },
    { term: 'bars', definition: 'Rap lyrics, specifically clever or well-crafted lines.', origin: 'Hip-hop slang', example: 'Daai bars was kwaai' },
    { term: 'flow', definition: 'The rhythm and delivery of a rapper\'s lyrics over a beat.', origin: 'Hip-hop terminology', example: 'Sy flow is on another level' },
    { term: 'heat', definition: 'A very good song or track. "That\'s heat" = that\'s fire.', origin: 'Hip-hop slang', example: 'Elke track op die album is heat' },
    { term: 'fire', definition: 'Excellent, high quality. "That\'s fire" = that\'s great.', origin: 'Universal contemporary slang', example: 'Die beat is fire' },
    { term: 'wave', definition: 'A music trend or cultural movement that others follow.', origin: 'Hip-hop slang', example: 'Esdeekid set die wave' },
    { term: 'on repeat', definition: 'Listening to a song over and over. Can\'t stop playing it.', origin: 'Music slang', example: 'Daai track is op repeat die week' },
    { term: 'feature', definition: 'A guest appearance on someone else\'s song.', origin: 'Music industry term', example: 'Hy het \'n feature op die album' },
    { term: 'collab', definition: 'A collaboration between artists.', origin: 'Music industry slang', example: 'Hulle twee het \'n collab gedruk' },
    { term: 'merch', definition: 'Merchandise — branded items sold by an artist.', origin: 'Music industry', example: 'Sy merch is uitverkoop' },

    // ── Status & Possessions ─────────────────────────────────────────────────────
    { term: 'whip', definition: 'A car. "My whip" = my car.', origin: 'American hip-hop', example: 'Wat ry hy? Nuwe whip' },
    { term: 'beemer', definition: 'A BMW car. Common status symbol.', origin: 'English car slang', example: 'Hy ry \'n beemer' },
    { term: 'ice', definition: 'Diamond jewellery. "Iced out" = covered in diamonds.', origin: 'American hip-hop', example: 'Hy het ice op sy neck' },
    { term: 'chain', definition: 'A gold/diamond necklace chain. Status symbol.', origin: 'Hip-hop culture', example: 'Sy chain blink in die son' },
    { term: 'rollie', definition: 'A Rolex watch. Luxury symbol.', origin: 'Rolex brand name', example: 'Hy dra \'n rollie' },
    { term: 'crib', definition: 'House, home. Where you live.', origin: 'American hip-hop', example: 'Kom na my crib' },
    { term: 'fresh', definition: 'New, clean, stylish. Looking good.', origin: 'Hip-hop/American English', example: 'Hy is fresh vanaand' },
    { term: 'cooked', definition: 'In serious trouble; also very intoxicated.', origin: 'Contemporary slang', example: 'Hy is gecooked' },

    // ── Relationships & Family ───────────────────────────────────────────────────
    { term: 'dayones', definition: 'Friends who have been with you from the beginning, day one.', origin: 'American slang', example: 'Die dayones bly lojaal' },
    { term: 'fam', definition: 'Family. Used broadly for close friends too.', origin: 'American hip-hop', example: 'Jy is fam vir my' },
    { term: 'kin', definition: 'Family members, relatives. Related people.', origin: 'English', example: 'Hy is kin van ons' },
    { term: 'blood', definition: 'A blood relative; or used broadly as a term of address for close friends.', origin: 'American hip-hop', example: 'Hy is my blood bra' },
    { term: 'ride for', definition: 'To support and defend someone no matter what.', origin: 'American hip-hop', example: 'Ek sal vir jou ride always' },
    { term: 'got your back', definition: 'To protect and support someone in any situation.', origin: 'Universal English', example: 'Ek het jou rug' },
    { term: 'plug in', definition: 'To connect someone with a resource or person they need.', origin: 'Cape Flats street slang', example: 'Ek sal jou plug in met sy' },
    { term: 'bless', definition: 'To share, give, or hook someone up with something.', origin: 'Universal', example: 'Bless vir my \'n stukkie brood' },

    // ── Common Verbs & Phrases ───────────────────────────────────────────────────
    { term: 'vat', definition: 'To take or grab something. "Vat jou goed" = take your stuff.', origin: 'Afrikaans', example: 'Vat die money en klap' },
    { term: 'klap', definition: 'To slap or hit. Also used as "run" or "go".', origin: 'Afrikaans', example: 'Hy het hom geklap' },
    { term: 'gooi', definition: 'To throw; also to put or do something. Very versatile Cape verb.', origin: 'Afrikaans', example: 'Gooi die beat aan' },
    { term: 'sê', definition: 'To say. Also used as a term of address like "yo".', origin: 'Afrikaans', example: 'Wat sê jy sê?' },
    { term: 'loop', definition: 'To walk or to go somewhere. "Laat loop" = let\'s go.', origin: 'Afrikaans', example: 'Ons loop na die hoek' },
    { term: 'kyk', definition: 'To look, watch, or see. "Kyk hoe" = look how.', origin: 'Afrikaans', example: 'Kyk wat hy doen nou' },
    { term: 'laat weet', definition: 'Let me know; let him know. Communication request.', origin: 'Afrikaans', example: 'Laat weet as jy arriveer' },
    { term: 'wag', definition: 'Wait; be patient.', origin: 'Afrikaans', example: 'Wag vir my hier' },
    { term: 'breek', definition: 'To break. "Tik het hom gebreek" = tik destroyed him.', origin: 'Afrikaans', example: 'Die pipe het hom gebreek' },
    { term: 'vergeet', definition: 'To forget. "Vergeet dit" = forget it.', origin: 'Afrikaans', example: 'Vergeet wat hy gesê het' },
    { term: 'belowe', definition: 'To promise. Used seriously in loyalty oaths.', origin: 'Afrikaans', example: 'Ek belowe op my lewe' },
    { term: 'swear', definition: 'To swear/promise. Also used as confirmation "I swear" = truly.', origin: 'English', example: 'Swear bra, dit is waar' },
    { term: 'onthou', definition: 'Remember. "Onthou waar jy vandaan kom" = remember where you from.', origin: 'Afrikaans', example: 'Onthou jou wortels altyd' },

    // ── Comparisons & Descriptions ───────────────────────────────────────────────
    { term: 'mad', definition: 'Very, extremely. Intensifier. "Mad nice" = very nice.', origin: 'AAVE', example: 'Dit is mad kwaai bra' },
    { term: 'lit', definition: 'Exciting, fun, on fire. Describes a great event.', origin: 'American slang', example: 'Die party was lit vanaand' },
    { term: 'cold', definition: 'Impressive, excellent. "That\'s cold" = that\'s impressive.', origin: 'American hip-hop', example: 'Daai vers was koud' },
    { term: 'sick', definition: 'Excellent, impressive. "That\'s sick" = that\'s amazing.', origin: 'Universal youth slang', example: 'Daai beat is sick' },
    { term: 'hard', definition: 'Impressive, intense, uncompromising. "Going hard" = giving max effort.', origin: 'American hip-hop', example: 'Die song is hard' },
    { term: 'slept on', definition: 'Underrated or overlooked. "People slept on him" = didn\'t recognise his talent.', origin: 'American hip-hop', example: 'Hy was te lank geslept op' },
    { term: 'different', definition: 'In a class of its own. "He\'s different" = exceptional.', origin: 'Contemporary slang', example: 'Daai artis is different man' },
    { term: 'on another level', definition: 'Far superior, beyond comparison.', origin: 'Universal', example: 'Sy skills is op \'n ander vlak' },
    { term: 'raw', definition: 'Unpolished but powerful. Authentic and genuine.', origin: 'Universal English', example: 'Sy storie is raw en ware' },
    { term: 'deep', definition: 'Meaningful, profound. "That\'s deep" = that hit hard emotionally.', origin: 'Universal English', example: 'Daai lyrics is diep' },

    // ── Pop culture SDK references ───────────────────────────────────────────────
    { term: 'addik', definition: 'Addict or someone hooked on something — substance or activity.', origin: 'Cape Flats Afrikaans', example: 'Hy is \'n addik vir die game' },
    { term: 'marapagik', definition: 'Aggressive, fierce or tough. A term to describe a dangerous individual.', origin: 'Cape Flats slang', example: 'Hy is marapagik man' },
    { term: 'liggen', definition: 'Lying down, laid back, or chilling. Also: to be at someone\'s place.', origin: 'Cape Afrikaans from "lê"', example: 'Ek liggen by my bra se plek' },
    { term: 'tele', definition: 'Far away, distant. "Liggen tele" = far away.', origin: 'Cape Afrikaans from "tele" (television/distance)', example: 'Hy bly tele van die drama' },
    { term: 'grafik', definition: 'Graphic, extreme, vivid. Used to describe intense or violent situations.', origin: 'Cape Flats slang', example: 'Die scene was grafik' },
    { term: 'neffens', definition: 'Beside, next to, alongside. Spatial and also used for "despite".', origin: 'Cape Afrikaans from "naas"', example: 'Hy sit neffens my' },
    { term: 'oppas', definition: 'To watch out or be careful. A warning.', origin: 'Afrikaans "oppas"', example: 'Oppas vir daai ou' },
    { term: 'gabba', definition: 'Friend, buddy. Same as bra but more specific to certain Cape Flats areas.', origin: 'Cape Flats slang', example: 'My gabba was daar' },
    { term: 'pomp', definition: 'To pump, to boost, or to have sex (crude). Context dependent.', origin: 'Afrikaans', example: 'Hy pomp die game op' },
    { term: 'smaak', definition: 'To like, to fancy, to be attracted to. "Hy smaak haar" = he likes her.', origin: 'Afrikaans', example: 'Ek smaak daai cherrie kwaai' },
    { term: 'stukkend', definition: 'Broken, destroyed. Can refer to objects, people, or situations.', origin: 'Afrikaans', example: 'Die kar is stukkend' },
    { term: 'bietjie', definition: 'A little, a small amount. "Net \'n bietjie" = just a little.', origin: 'Afrikaans', example: 'Gee vir my net \'n bietjie' },
    { term: 'miskien', definition: 'Maybe, perhaps. Used in cautious statements.', origin: 'Afrikaans', example: 'Miskien sal dit beter gaan' },
    { term: 'nooit', definition: 'Never. Also used as "no way!" exclamation.', origin: 'Afrikaans', example: 'Nooit bra, dit sal nooit gebeur nie' },
    { term: 'altyd', definition: 'Always. A commitment word used in loyalty statements.', origin: 'Afrikaans', example: 'Ek sal altyd hier wees' },
    { term: 'seker', definition: 'Sure, certain, probably. "Certainly" or "I think so."', origin: 'Afrikaans', example: 'Hy sal seker kom' },
    { term: 'waarheid', definition: 'Truth. In street culture: "speak the truth."', origin: 'Afrikaans', example: 'Daai is die waarheid' },
    { term: 'lewe', definition: 'Life. "Op my lewe" = on my life (oath of sincerity).', origin: 'Afrikaans', example: 'Op my lewe ek het dit nie gedoen nie' },
    { term: 'dood', definition: 'Dead, death. Used literally or as intensifier ("dead serious").', origin: 'Afrikaans', example: 'Hy is dood ernstig' },
    { term: 'moeilikheid', definition: 'Trouble, difficulty. "In die moeilikheid" = in trouble.', origin: 'Afrikaans', example: 'Hy is in groot moeilikheid' },

    // ── Verbs used uniquely in Cape rap ─────────────────────────────────────────
    { term: 'shine', definition: 'To glow up, to succeed, to show your best self.', origin: 'Universal English', example: 'Dis sy tyd om te shine' },
    { term: 'grind out', definition: 'To work intensely until you achieve something.', origin: 'Hip-hop culture', example: 'Hy grind out elke dag' },
    { term: 'ball out', definition: 'To spend money lavishly; to live extravagantly.', origin: 'American hip-hop', example: 'Hy bal uit die naand' },
    { term: 'ball', definition: 'To live luxuriously or play sport. "He\'s balling" = he\'s wealthy.', origin: 'American hip-hop', example: 'Hy is besig om te bal' },
    { term: 'switch on', definition: 'To become aggressive or dangerous quickly.', origin: 'Cape Flats street slang', example: 'Moenie hom switch on nie' },
    { term: 'cook', definition: 'To do something brilliantly; to absolutely excel.', origin: 'American slang', example: 'Hy cook op daai beat' },
    { term: 'murk', definition: 'To defeat or destroy completely; to kill in rap context.', origin: 'American hip-hop', example: 'Hy het die ander MC gemurk' },
    { term: 'snap', definition: 'To rap exceptionally well; "he snapped" = incredible performance.', origin: 'American hip-hop', example: 'Hy het gesnappe op daai verse' },
    { term: 'bodied', definition: 'To outperform someone completely; also can mean killed.', origin: 'Hip-hop slang', example: 'Hy het die beat gebodied' },
    { term: 'clap back', definition: 'To retaliate with words (diss track) or actions.', origin: 'American hip-hop', example: 'Hy clap terug met \'n diss track' },

    // ── Police & Law ───────────────────────────────────────────────────────────
    { term: 'boere', definition: 'The police. Afrikaans for "farmers" but universally used for cops on the Cape Flats.', origin: 'Cape Flats Afrikaans', example: 'Die boere is in die wyk' },
    { term: 'cherries', definition: 'Police sirens/lights. The red and blue flashing lights on cop cars.', origin: 'Cape Flats slang', example: 'Ek sien cherries om die hoek' },
    { term: 'jacked', definition: 'Arrested, busted, caught by police.', origin: 'American slang adopted', example: 'Hy was gejacked by die boere' },
    { term: 'bail', definition: 'To leave quickly; also literal bail money to get released from jail.', origin: 'English', example: 'Ons moet bail hier' },
    { term: 'tronk', definition: 'Prison, jail. Doing time.', origin: 'Afrikaans', example: 'Hy sit in die tronk al drie jaar' },
    { term: 'binne', definition: 'Inside — specifically inside prison.', origin: 'Afrikaans', example: 'Hy is binne vir vyf jaar' },
    { term: 'warrant', definition: 'An arrest warrant. "There\'s a warrant on him."', origin: 'English legal term', example: 'Daar is \'n warrant op hom' },
    { term: 'case', definition: 'A criminal case; also "catching a case" = getting arrested.', origin: 'Legal English', example: 'Hy het \'n case gevang' },
    { term: 'snitch', definition: 'An informer who tells police about criminal activity.', origin: 'American English', example: 'Niemand hou van \'n snitch nie' },
    { term: 'five-o', definition: 'The police. From "Hawaii Five-O" TV show.', origin: 'American slang', example: 'Five-o is op die pad' },
    { term: 'run', definition: 'To flee from police or danger.', origin: 'Universal English', example: 'Hy moes run van die boere' },
    { term: 'clean', definition: 'Not carrying any illegal items; also free from criminal record.', origin: 'Street slang', example: 'Hy is clean, niks op hom nie' },

    // ── Religion & Oaths ───────────────────────────────────────────────────────
    { term: 'wallahi', definition: 'I swear to God. Arabic oath used widely on the Cape Flats (Muslim community).', origin: 'Arabic via Cape Malay', example: 'Wallahi bra, dit is die waarheid' },
    { term: 'insha\'Allah', definition: 'God willing. Used to express hope for the future.', origin: 'Arabic via Cape Malay', example: 'Insha\'Allah sal dit reg kom' },
    { term: 'bismillah', definition: 'In the name of God. Said before eating or starting something.', origin: 'Arabic via Cape Malay', example: 'Bismillah, ons begin' },
    { term: 'masjid', definition: 'Mosque. Place of Islamic worship, central to many Cape Flats communities.', origin: 'Arabic', example: 'Hy gaan masjid toe elke Vrydag' },
    { term: 'haram', definition: 'Forbidden in Islam; also used casually for anything sinful or wrong.', origin: 'Arabic via Cape Malay', example: 'Daai is haram bra' },
    { term: 'dua', definition: 'A personal prayer or supplication to God.', origin: 'Arabic', example: 'Maak dua vir hom' },
    { term: 'sabr', definition: 'Patience. Having endurance through hardship.', origin: 'Arabic via Cape Malay', example: 'Sabr bra, jou tyd kom' },
    { term: 'karamah', definition: 'Dignity, honor. Used to describe someone with self-respect.', origin: 'Arabic via Cape Malay', example: 'Hy het karamah' },

    // ── Food & Drink (Cape Flats specific) ─────────────────────────────────────
    { term: 'koesisters', definition: 'Cape Malay spiced doughnuts. Cultural staple at every event.', origin: 'Cape Malay cuisine', example: 'Auntie se koesisters is die beste' },
    { term: 'samoosas', definition: 'Triangular deep-fried pastries with spiced filling. Cape Malay staple.', origin: 'Cape Malay via Indian', example: 'Die samoosas is uitverkoop' },
    { term: 'roti', definition: 'Flatbread. Often filled with curry for a roti roll.', origin: 'Indian via Cape Malay', example: 'Koop \'n roti by die corner shop' },
    { term: 'bunny chow', definition: 'Hollowed loaf of bread filled with curry. Durban origin, loved in Cape.', origin: 'Durban Indian/South African', example: 'Ons eet bunny chow vanaand' },
    { term: 'slaai', definition: 'Salad. In Cape context often refers to a side dish or something cool.', origin: 'Afrikaans', example: 'Gooi die slaai saam' },
    { term: 'pap', definition: 'Maize porridge. Staple South African food, especially in townships.', origin: 'Afrikaans/Sotho', example: 'Pap en wors op die braai' },
    { term: 'slap chips', definition: 'Soft, thick-cut fries unique to Cape Town. Essential in a gatsby.', origin: 'Cape Town food culture', example: 'Die slap chips is lekker sout' },
    { term: 'cooldrink', definition: 'Any carbonated soft drink (soda). South African term.', origin: 'South African English', example: 'Koop \'n cooldrink by die shop' },

    // ── Weather & Time ─────────────────────────────────────────────────────────
    { term: 'the southeaster', definition: 'The strong Cape Town wind. "The Cape Doctor." Summer phenomenon.', origin: 'Cape Town geographic', example: 'Die southeaster waai weer vandag' },
    { term: 'nou-nou', definition: 'In a moment, soon, shortly. Classic SA time expression.', origin: 'Afrikaans', example: 'Ek kom nou-nou' },
    { term: 'netnou', definition: 'Just now; soon; or "be careful or else..." depending on tone.', origin: 'Afrikaans', example: 'Netnou val jy' },
    { term: 'more', definition: 'Tomorrow. Afrikaans.', origin: 'Afrikaans', example: 'Ons praat more' },
    { term: 'gister', definition: 'Yesterday.', origin: 'Afrikaans', example: 'Gister was dit hectic' },
    { term: 'aand', definition: 'Evening, night. "Goeie aand" = good evening.', origin: 'Afrikaans', example: 'Die aand was lank' },
    { term: 'oggend', definition: 'Morning.', origin: 'Afrikaans', example: 'Vroeg oggend al op die pad' },

    // ── Transport ──────────────────────────────────────────────────────────────
    { term: 'taxi', definition: 'Minibus taxi — the main form of public transport in SA townships. Not a metered cab.', origin: 'South African context', example: 'Vat die taxi na die Kaap' },
    { term: 'gaatjie', definition: 'The taxi conductor who collects fares and calls out destinations.', origin: 'Cape Flats/Afrikaans', example: 'Die gaatjie skel weer' },
    { term: 'rank', definition: 'Taxi rank — where minibus taxis depart and arrive.', origin: 'South African English', example: 'Ons ontmoet by die rank' },
    { term: 'ry', definition: 'To drive or ride. "Ry saam" = come along for the ride.', origin: 'Afrikaans', example: 'Hy ry \'n nuwe BMW' },
    { term: 'lift', definition: 'A ride in someone\'s car. "Gee my \'n lift" = give me a ride.', origin: 'South African English', example: 'Kan jy vir my \'n lift gee?' },
    { term: 'petrol', definition: 'Gasoline/fuel. "No petrol" can mean no money or no energy.', origin: 'South African English', example: 'Die kar het nie petrol nie' },

    // ── Education & Streets ────────────────────────────────────────────────────
    { term: 'matric', definition: 'Final year of high school (Grade 12). A major achievement on the Flats.', origin: 'South African education system', example: 'Hy het sy matric gemaak' },
    { term: 'skool', definition: 'School. Also slang for learning life lessons the hard way.', origin: 'Afrikaans', example: 'Die strate is sy skool' },
    { term: 'lem', definition: 'A knife or blade. Carried for protection in dangerous areas.', origin: 'Afrikaans', example: 'Hy dra \'n lem by hom' },
    { term: 'shank', definition: 'A makeshift knife or blade; to stab someone.', origin: 'Prison slang', example: 'Hy het hom geshank in die tronk' },
    { term: 'jacket', definition: 'Bulletproof vest. Worn for protection in gang areas.', origin: 'Street slang', example: 'Hy dra \'n jacket onder sy trui' },
    { term: 'chrome', definition: 'A gun, specifically a silver/metallic firearm.', origin: 'American hip-hop', example: 'Hy het chrome in die kar' },
    { term: 'piece', definition: 'A firearm/gun. "Carry a piece" = carry a gun.', origin: 'American slang', example: 'Moenie sonder \'n piece gaan nie' },

    // ── Body & Health ──────────────────────────────────────────────────────────
    { term: 'siek', definition: 'Sick. Also used as slang for "crazy good" like English "sick."', origin: 'Afrikaans', example: 'Daai track is siek bra' },
    { term: 'befok', definition: 'Crazy, insane. Can be positive ("that\'s crazy good") or negative.', origin: 'Afrikaans expletive', example: 'Hy is befok in sy kop' },
    { term: 'gesuip', definition: 'Very drunk. Literally "gulped down."', origin: 'Afrikaans', example: 'Hy was gesuip laasnaand' },
    { term: 'naar', definition: 'Nauseous, feeling sick. "Ek voel naar."', origin: 'Afrikaans', example: 'Ek voel naar van die drank' },
    { term: 'pyn', definition: 'Pain, suffering. Used literally and metaphorically.', origin: 'Afrikaans', example: 'Die pyn is real in die flats' },
    { term: 'vet', definition: 'Fat. Also means rich, loaded, or having plenty.', origin: 'Afrikaans', example: 'Sy wallet is vet' },

    // ── Social Media & Modern ──────────────────────────────────────────────────
    { term: 'sus', definition: 'Suspicious, shady, not trustworthy. From "suspect."', origin: 'Internet/gaming slang', example: 'Daai ou is sus bra' },
    { term: 'ghosting', definition: 'Disappearing from communication. Ignoring someone completely.', origin: 'Modern dating slang', example: 'Hy ghost al die tyd' },
    { term: 'ratio', definition: 'To get more negative responses than positive; being outvoted or outdone.', origin: 'Internet/Twitter slang', example: 'Hy was ge-ratio op die post' },
    { term: 'W', definition: 'A win, a success, a positive outcome.', origin: 'Internet slang', example: 'Daai was \'n massive W' },
    { term: 'L', definition: 'A loss, a failure, an embarrassment.', origin: 'Internet slang', example: 'Hy vat L na L' },
    { term: 'mid', definition: 'Average, mediocre, nothing special.', origin: 'Internet/TikTok slang', example: 'Daai song is mid' },
    { term: 'bussin', definition: 'Extremely good, especially referring to food or music.', origin: 'American TikTok slang', example: 'Die gatsby is bussin' },
    { term: 'slay', definition: 'To do something exceptionally well; to kill it.', origin: 'American pop culture', example: 'Sy slay daai outfit' },
    { term: 'bet', definition: 'Agreement, confirmation. "Okay, sounds good."', origin: 'American AAVE', example: 'Bet bra, ek is daar' },
    { term: 'ong', definition: 'Short for "on God" — a strong affirmation.', origin: 'American AAVE', example: 'Ong bra dit was die beste' },

    // ── Insults & Disrespect ───────────────────────────────────────────────────
    { term: 'poes', definition: 'Very strong Cape Flats expletive. Used as an insult or intensifier.', origin: 'Afrikaans vulgar', example: 'Hy is \'n poes' },
    { term: 'doos', definition: 'An idiot, a fool. Strong but common Cape insult.', origin: 'Afrikaans vulgar', example: 'Moenie \'n doos wees nie' },
    { term: 'gat', definition: 'Literally "backside." Used as an insult or for emphasis.', origin: 'Afrikaans', example: 'Hy praat uit sy gat' },
    { term: 'moer', definition: 'To beat up; also an expletive intensifier. "Gaan moer hom."', origin: 'Afrikaans', example: 'Ek gaan hom moer' },
    { term: 'dom', definition: 'Stupid, dumb. "Dom ding" = stupid thing.', origin: 'Afrikaans', example: 'Moenie so dom wees nie' },
    { term: 'simpel', definition: 'Simple-minded, stupid. Used to call someone foolish.', origin: 'Afrikaans', example: 'Hy is simpel in sy kop' },
    { term: 'poephol', definition: 'Very vulgar insult. Literally anatomical, used like "a**hole."', origin: 'Afrikaans vulgar', example: 'Daai ou is \'n poephol' },
    { term: 'bliksem', definition: 'To hit/beat someone; also used as an exclamation of surprise.', origin: 'Afrikaans', example: 'Ek sal jou bliksem' },

    // ── Cape Malay Culture ─────────────────────────────────────────────────────
    { term: 'Bo-Kaap', definition: 'The colourful neighbourhood above Cape Town CBD. Heart of Cape Malay culture.', origin: 'Geographic/Cultural', example: 'Die Bo-Kaap is beautiful' },
    { term: 'Labarang', definition: 'Eid celebration, especially Eid al-Fitr. Major Cape Malay festival.', origin: 'Cape Malay culture', example: 'Labarang is \'n groot dag' },
    { term: 'boerewors', definition: 'Traditional South African sausage. Braai essential.', origin: 'Afrikaans', example: 'Gooi die boerewors op die vuur' },
    { term: 'dhaltjies', definition: 'Chili bites — deep-fried spiced snacks. Cape Malay party food.', origin: 'Cape Malay cuisine', example: 'Die dhaltjies is lekker spicy' },
    { term: 'denningvleis', definition: 'Sweet and sour braised lamb. Classic Cape Malay dish.', origin: 'Cape Malay cuisine', example: 'Ma se denningvleis is die beste' },

    // ── Xhosa Borrowings (used in SDK) ─────────────────────────────────────────
    { term: 'mzansi', definition: 'South Africa. Xhosa term meaning "south." National nickname.', origin: 'Xhosa', example: 'Mzansi is ons land' },
    { term: 'madala', definition: 'Old man, elder. Respectful Xhosa term.', origin: 'Xhosa/Zulu', example: 'Die madala ken die storie' },
    { term: 'sharp-sharp', definition: 'All good, cool, fine. Double affirmation.', origin: 'South African township slang', example: 'Sharp-sharp bra, alles is reg' },
    { term: 'ayoba', definition: 'Cool, great, awesome. South African exclamation of approval.', origin: 'Zulu/Township slang', example: 'Ayoba, daai is lekker' },
    { term: 'yebo', definition: 'Yes. Zulu affirmative used across South Africa.', origin: 'Zulu', example: 'Yebo bra, ek is in' },
    { term: 'sawubona', definition: 'Hello, I see you. Respectful Zulu/Xhosa greeting.', origin: 'Zulu/Xhosa', example: 'Sawubona maat' },
    { term: 'ubuntu', definition: '"I am because we are." African philosophy of community and shared humanity.', origin: 'Zulu/Xhosa philosophy', example: 'Ubuntu is alles vir ons' },
    { term: 'indaba', definition: 'A meeting, discussion, or conference. Used in street context for a serious talk.', origin: 'Zulu/Xhosa', example: 'Ons het \'n indaba gehad' },
    { term: 'shebeen', definition: 'An informal tavern/bar in a township. Social gathering spot.', origin: 'Irish via South African', example: 'Ons gaan shebeen toe vanaand' },
    { term: 'tsotsi', definition: 'A street criminal, gangster. Classic township term.', origin: 'Sesotho/South African', example: 'Hy is \'n tsotsi van die strate' },

    // ── Numbers Gang Culture ───────────────────────────────────────────────────
    { term: 'salute', definition: 'A gang greeting or sign of respect within prison gang hierarchy.', origin: 'Numbers gang culture', example: 'Hy salute die nommer' },
    { term: 'nommer', definition: 'Number — refers to prison gang affiliation (26, 27, or 28).', origin: 'Cape prison gang system', example: 'Wat is jou nommer?' },
    { term: 'fransman', definition: 'The "general" or leader within the Numbers gang structure.', origin: 'Numbers gang hierarchy', example: 'Die fransman gee die orders' },
    { term: 'sabela', definition: 'The secret coded language used by Numbers gangs in prison.', origin: 'Numbers gang culture', example: 'Hy praat sabela binne' },
    { term: 'bandiet', definition: 'A convict, prisoner. Often used self-referentially with pride.', origin: 'Afrikaans from "bandit"', example: 'Hy is \'n ou bandiet' },
    { term: 'gevang', definition: 'Caught, arrested. "Hy is gevang" = he was caught/arrested.', origin: 'Afrikaans', example: 'Hy is gevang laasnaand' },

    // ── Additional Street Phrases ──────────────────────────────────────────────
    { term: 'sak af', definition: 'Come down, calm down. Also: to go to someone\'s place.', origin: 'Afrikaans Cape Flats', example: 'Sak af na my toe' },
    { term: 'deurmekaar', definition: 'Confused, mixed up, chaotic. "Dit is deurmekaar" = it\'s a mess.', origin: 'Afrikaans', example: 'Sy kop is deurmekaar' },
    { term: 'gatvol', definition: 'Fed up, had enough. Very common expressive term.', origin: 'Afrikaans', example: 'Ek is gatvol vir die nonsens' },
    { term: 'voetsek', definition: 'Go away (very rude). Used to chase someone or a dog off.', origin: 'Afrikaans from Dutch', example: 'Voetsek hier weg!' },
    { term: 'jammer', definition: 'Sorry, apologetic. "Ek is jammer" = I\'m sorry.', origin: 'Afrikaans', example: 'Jammer bra, ek het gemis' },
    { term: 'lekker bly', definition: 'To live well, stay good. A wish for someone\'s wellbeing.', origin: 'Afrikaans', example: 'Bly lekker bra' },
    { term: 'skiet', definition: 'To shoot. Literally and figuratively.', origin: 'Afrikaans', example: 'Hulle skiet in die nag' },
    { term: 'stamp', definition: 'To stomp or kick. Physical attack.', origin: 'Afrikaans', example: 'Hulle het hom gestamp' },
    { term: 'skop', definition: 'To kick. "Skop hom uit" = kick him out.', origin: 'Afrikaans', example: 'Hy het die bal geskop' },
    { term: 'sit', definition: 'To sit; also to do time in prison. "Hy sit" = he\'s in jail.', origin: 'Afrikaans', example: 'Hy sit al twee jaar' },
    { term: 'staan', definition: 'To stand; to represent. "Ons staan saam" = we stand together.', origin: 'Afrikaans', example: 'Ons staan vir die wyk' },
    { term: 'val', definition: 'To fall; to get caught; to die. "Hy het geval" = he fell/died.', origin: 'Afrikaans', example: 'Moenie val vir die trap nie' },
    { term: 'brand', definition: 'To burn. "Die huis brand" = house is on fire. Also to betray.', origin: 'Afrikaans', example: 'Hy het ons gebrand' },
    { term: 'steel', definition: 'To steal. "Moenie steel nie" = don\'t steal.', origin: 'Afrikaans', example: 'Hulle steel als in die wyk' },
    { term: 'lieg', definition: 'To lie, to be dishonest. "Hy lieg" = he\'s lying.', origin: 'Afrikaans', example: 'Moenie vir my lieg nie' },
    { term: 'draai', definition: 'To turn, to roll. "Draai \'n zol" = roll a joint. Also to change direction.', origin: 'Afrikaans', example: 'Draai om en loop' },
    { term: 'maak', definition: 'To make, to do. "Maak plan" = figure it out, make a plan.', origin: 'Afrikaans', example: 'Ons moet \'n plan maak' },
    { term: 'plan', definition: 'A scheme, a way forward. "Maak \'n plan" = find a solution.', origin: 'Afrikaans/English', example: 'Het jy \'n plan?' },
    { term: 'probleem', definition: 'Problem. "Geen probleem" = no problem.', origin: 'Afrikaans', example: 'Dis \'n groot probleem' },
    { term: 'antwoord', definition: 'An answer. "Hy het nie \'n antwoord nie" = he has no answer.', origin: 'Afrikaans', example: 'Gee my \'n antwoord' },
    { term: 'dream', definition: 'A dream or ambition. "Chase the dream" is a big SDK theme.', origin: 'Universal English', example: 'Ons chase die dream elke dag' },
    { term: 'struggle', definition: 'The daily fight to survive, especially in poverty. Deep SA resonance.', origin: 'South African political/social', example: 'Die struggle is real hierso' },
    { term: 'survive', definition: 'To make it through. Core Cape Flats ethic: just surviving.', origin: 'Universal English', example: 'Ons survive elke dag' },
    { term: 'free', definition: 'Freedom. Out of prison. Also the aspiration to escape poverty.', origin: 'Universal English', example: 'Hy wil vry wees van die strate' },
    { term: 'trap house', definition: 'A house used for drug dealing. A base of operations.', origin: 'American hip-hop', example: 'Die trap house was warm' },
    { term: 'posted up', definition: 'Standing or hanging out in a particular spot.', origin: 'American hip-hop', example: 'Hy is posted up op die hoek' },
    { term: 'lowrider', definition: 'A customized car that rides low. Status symbol in Cape Flats car culture.', origin: 'American car culture', example: 'Sy lowrider is kwaai' },
    { term: 'spinning', definition: 'Car spinning — doing doughnuts with a car. Big Cape Flats entertainment.', origin: 'South African car culture', example: 'Hulle spin weer op die parkeerterrein' },
    { term: 'stoep', definition: 'Front porch or veranda. Where people sit and socialise on the Cape Flats.', origin: 'Afrikaans from Dutch', example: 'Ons sit op die stoep en kuier' },
    { term: 'kuier', definition: 'To visit, to socialise, to hang out. A core Cape social activity.', origin: 'Afrikaans', example: 'Kom kuier by ons' },
    { term: 'suip', definition: 'To drink heavily, to booze. "Hy suip" = he drinks a lot.', origin: 'Afrikaans', example: 'Hy suip elke naweek' },
    { term: 'dagbreek', definition: 'Daybreak, dawn. The start of a new day on the Flats.', origin: 'Afrikaans', example: 'By dagbreek is ons op die pad' },
    { term: 'donker', definition: 'Dark. "In die donker" = in the dark (literally and figuratively).', origin: 'Afrikaans', example: 'Die strate is donker vanaand' },
    { term: 'lig', definition: 'Light. "Bring die lig" = bring the light (hope, truth, or attention).', origin: 'Afrikaans', example: 'Hy bring lig na die wyk' },
    { term: 'bloed', definition: 'Blood. Used for family ties and sworn loyalty ("blood brothers").', origin: 'Afrikaans', example: 'Bloed is dikker as water' },
    { term: 'hart', definition: 'Heart. "Met hart" = with passion. Core emotional SDK theme.', origin: 'Afrikaans', example: 'Hy rap met hart' },
    { term: 'siel', definition: 'Soul. "Op my siel" = on my soul (oath). Deep emotional expression.', origin: 'Afrikaans', example: 'Ek belowe op my siel' },
    { term: 'sterk', definition: 'Strong. Physical and mental strength. "Bly sterk" = stay strong.', origin: 'Afrikaans', example: 'Ons is sterk genoeg' },
    { term: 'kanala', definition: 'Please, I beg you. A plea or earnest request.', origin: 'Cape Malay/Afrikaans', example: 'Kanala bra, help my uit' },
    { term: 'aweh', definition: 'Hello, cool, yes, alright. Versatile Cape Flats greeting/affirmation.', origin: 'Cape Flats slang', example: 'Aweh bra, hoe gaan dit?' },
    { term: 'hosh', definition: 'Greeting. Also means "let\'s go" or "deal." Gang-origin greeting.', origin: 'Cape Flats gang & street culture', example: 'Hosh bra, ons is reg' },
    { term: 'djy', definition: 'You. Cape Flats phonetic spelling of "jy" (you).', origin: 'Kaaps dialect', example: 'Djy weet mos hoe dit werk' },
    { term: 'issit', definition: '"Is it?" — expression of surprise or disbelief. Universal SA.', origin: 'South African English', example: 'Issit? Ek het nie geweet nie' },
    { term: 'bergie', definition: 'A homeless person in Cape Town, especially around Table Mountain.', origin: 'Afrikaans from "berg" (mountain)', example: 'Die bergie ken die strate' },
    { term: 'gattas', definition: 'Street soccer/football. Played barefoot on the Cape Flats.', origin: 'Cape Flats slang', example: 'Die laaities speel gattas op die veld' },
    { term: 'jive', definition: 'Nonsense talk; also a South African boxed wine brand.', origin: 'South African English', example: 'Hy praat jive' },
    { term: 'nxa', definition: 'A tongue click expressing annoyance or frustration.', origin: 'Xhosa/Zulu', example: 'Nxa, vergeet dit man' },
    { term: 'aitsa', definition: 'Exclamation of surprise or admiration. Like "wow!"', origin: 'South African slang', example: 'Aitsa, daai was heavy!' },

    // ── Additional Cape Flats Expressions ──────────────────────────────────────
    { term: 'bossiekop', definition: 'Someone with messy or curly hair. Lighthearted insult.', origin: 'Afrikaans Cape Flats', example: 'Kyk daai bossiekop se hare' },
    { term: 'chommie', definition: 'Close friend, buddy. Very friendly and casual.', origin: 'South African English from "chum"', example: 'Hy is my chommie van kleintyd af' },
    { term: 'dwaal', definition: 'To wander aimlessly or be confused. "In a dwaal" = spaced out.', origin: 'Afrikaans', example: 'Hy loop in ’n dwaal rond' },
    { term: 'gawie', definition: 'An uncool or dorky person. Lighthearted put-down.', origin: 'Cape Flats slang', example: 'Moenie so gawie wees nie' },
    { term: 'jaag', definition: 'To chase, pursue. "Jaag die paper" = chase the money.', origin: 'Afrikaans', example: 'Ons jaag the paper elke dag' },
    { term: 'kak', definition: 'Rubbish, nonsense, bad. Strong but common expletive.', origin: 'Afrikaans', example: 'Daai is kak bra' },
    { term: 'kennis', definition: 'An acquaintance. Someone you know but aren’t close to.', origin: 'Afrikaans', example: 'Hy is net ’n kennis' },
    { term: 'korreltjie', definition: 'A tiny amount; also used affectionately for someone small.', origin: 'Afrikaans diminutive', example: 'Net ’n korreltjie suiker' },
    { term: 'lank', definition: 'Very, really, a lot. Intensifier. "Lank kwaai" = very cool.', origin: 'Afrikaans Cape Flats', example: 'Daai is lank kwaai' },
    { term: 'miff', definition: 'Mean, stingy, or tight with money.', origin: 'Cape Flats slang', example: 'Hy is miff met sy geld' },
    { term: 'naar wees', definition: 'To feel nauseous or disgusted by someone’s behavior.', origin: 'Afrikaans', example: 'Hy maak my naar' },
    { term: 'oes', definition: 'To hit or punch someone. A physical confrontation.', origin: 'Afrikaans Cape Flats', example: 'Hy het hom ge-oes' },
    { term: 'parra', definition: 'Paranoid, anxious, worried about something.', origin: 'Cape Flats slang from "paranoid"', example: 'Moenie so parra wees nie' },
    { term: 'rand', definition: 'South African currency. Also used generically for money.', origin: 'South African', example: 'Het jy vyf rand?' },
    { term: 'skelm', definition: 'A crook, a thief, someone untrustworthy. Also: secretly.', origin: 'Afrikaans', example: 'Hy is ’n skelm' },
    { term: 'twak', definition: 'Nonsense, rubbish. Also literally tobacco.', origin: 'Afrikaans', example: 'Moenie twak praat nie' },
    { term: 'vars', definition: 'Fresh, new. "Vars clothes" = new clothes.', origin: 'Afrikaans', example: 'Sy vars takkies is kwaai' },
    { term: 'windgat', definition: 'Someone who is arrogant, a showoff. "Big headed."', origin: 'Afrikaans', example: 'Hy is ’n windgat' },
    { term: 'wragtag', definition: 'Truly, honestly. An oath meaning "really and truly."', origin: 'Afrikaans', example: 'Wragtag bra, dit was so' },
    { term: 'yster', definition: 'Iron. Used to mean someone tough or a weapon.', origin: 'Afrikaans', example: 'Hy is hard soos yster' },
    { term: 'baie', definition: 'Very, much, lots. Common intensifier.', origin: 'Afrikaans', example: 'Baie dankie bra' },
    { term: 'binnekort', definition: 'Soon, shortly, in a short while.', origin: 'Afrikaans', example: 'Hy kom binnekort' },
    { term: 'dié', definition: 'This one. Used for emphasis pointing to something specific.', origin: 'Afrikaans', example: 'Dié is die one' },
    { term: 'elke', definition: 'Every, each. "Elke dag" = every day.', origin: 'Afrikaans', example: 'Elke dag is ’n hustle' },
    { term: 'gevaarlik', definition: 'Dangerous. Used literally and as slang for impressive.', origin: 'Afrikaans', example: 'Daai ou is gevaarlik' },
    { term: 'hoe', definition: 'How. "Hoe gaan dit?" = how’s it going?', origin: 'Afrikaans', example: 'Hoe lyk dit vanaand?' },
    { term: 'kaalvoet', definition: 'Barefoot. Growing up barefoot on the Flats is a common childhood memory.', origin: 'Afrikaans', example: 'Ons het kaalvoet grootgeword' },
    { term: 'kwêla', definition: 'A style of South African music. Also means to climb/get on.', origin: 'Zulu/Township culture', example: 'Kwêla musiek is lekker' },
    { term: 'lag', definition: 'To laugh. "Hulle lag vir hom" = they laugh at him.', origin: 'Afrikaans', example: 'Moenie vir hom lag nie' },
    { term: 'mal', definition: 'Crazy, mad. "Hy is mal" = he’s crazy.', origin: 'Afrikaans', example: 'Hy is mal in sy kop' },
    { term: 'nêrens', definition: 'Nowhere. "Nêrens om te gaan" = nowhere to go.', origin: 'Afrikaans', example: 'Daar is nêrens om te run nie' },
    { term: 'oop', definition: 'Open. "Oop maak" = open up. Also vulnerable.', origin: 'Afrikaans', example: 'Hy het sy hart oopgemaak' },
    { term: 'praat', definition: 'To talk, to speak. "Praat saam" = talk with us.', origin: 'Afrikaans', example: 'Hy praat te veel' },
    { term: 'ruit', definition: 'Window. "Deur die ruit" = through the window.', origin: 'Afrikaans', example: 'Hulle het die ruit gebreek' },
    { term: 'sonop', definition: 'Sunrise. Poetic SDK reference to new beginnings.', origin: 'Afrikaans', example: 'By sonop is ons op' },
    { term: 'teen', definition: 'Against. "Teen die wêreld" = against the world.', origin: 'Afrikaans', example: 'Ons teen die wêreld' },
    { term: 'uitgesort', definition: 'Sorted out, taken care of. "Dit is uitgesort" = it’s handled.', origin: 'Afrikaans', example: 'Die probleem is uitgesort' },
    { term: 'verkeerd', definition: 'Wrong, incorrect. "Die verkeerde pad" = the wrong path.', origin: 'Afrikaans', example: 'Hy is op die verkeerde pad' },
    { term: 'wakker', definition: 'Awake, alert. "Bly wakker" = stay alert/woke.', origin: 'Afrikaans', example: 'Bly wakker op die strate' },
    { term: 'doss', definition: 'Lazy, idle, not doing anything. Also: to sleep rough.', origin: 'Cape Flats slang', example: 'Hy doss die heele dag' },
    { term: 'babbelas', definition: 'A hangover. The day-after feeling from too much drank.', origin: 'Zulu via Afrikaans', example: 'Ek het ’n vreeslike babbelas' },
    { term: 'bakgat', definition: 'Excellent, great, fantastic. Similar to "cool."', origin: 'Afrikaans', example: 'Daai was bakgat bra' },
    { term: 'blaps', definition: 'To steal or rob someone quickly. A snatch.', origin: 'Cape Flats slang', example: 'Hulle het sy foon geblaps' },
    { term: 'bunny', definition: 'A gullible or naive person. Easy to fool.', origin: 'English via Cape Flats', example: 'Moenie ’n bunny wees nie' },
    { term: 'charfe', definition: 'Bad looking, ugly, unappealing.', origin: 'Cape Flats slang', example: 'Daai plek is charfe' },
    { term: 'connections', definition: 'Contacts, people who can help you get things done.', origin: 'Universal English', example: 'Hy het connections oral' },
    { term: 'doef', definition: 'The bass in music. Also a hit or punch.', origin: 'Afrikaans onomatopoeia', example: 'Die doef in daai beat is kwaai' },
    { term: 'entjie', definition: 'A cigarette butt; also a short cigarette.', origin: 'Afrikaans diminutive', example: 'Het jy ’n entjie vir my?' },
    { term: 'fokken', definition: 'Very common Afrikaans intensifier/expletive. Like the F-word.', origin: 'Afrikaans from Dutch', example: 'Dis fokken kwaai' },
    { term: 'gatvol vir', definition: 'Fed up with, had enough of something specific.', origin: 'Afrikaans', example: 'Ek is gatvol vir die drama' },
    { term: 'haak', definition: 'A hook; also to grab or catch someone.', origin: 'Afrikaans', example: 'Hulle het hom ingehaak' },
    { term: 'innie', definition: 'In the. Cape dialect contraction of "in die."', origin: 'Kaaps dialect', example: 'Hy bly innie flats' },
    { term: 'jislaaik', definition: 'Exclamation of shock or amazement. Like "jeez!"', origin: 'Afrikaans', example: 'Jislaaik, wat het net gebeur?' },
    { term: 'klaar', definition: 'Finished, done, complete. "Ek is klaar" = I’m done.', origin: 'Afrikaans', example: 'Ons is klaar met daai' },
    { term: 'laaities', definition: 'Young boys, kids. Plural of laaitie.', origin: 'Cape Flats slang', example: 'Die laaities hardloop in die strate' },
    { term: 'moeg', definition: 'Tired, exhausted. "Ek is moeg" = I’m tired.', origin: 'Afrikaans', example: 'Ek is moeg van die hustle' },
    { term: 'nè', definition: 'Right? Isn’t it? A tag question seeking confirmation.', origin: 'Afrikaans', example: 'Dis kwaai nè?' },
    { term: 'ou', definition: 'A guy, a dude. Generic term for a man.', origin: 'Afrikaans', example: 'Daai ou is wild' },
    { term: 'penga', definition: 'Crazy, insane. More intense than "mal."', origin: 'Cape Flats slang', example: 'Hy is penga in sy kop' },
    { term: 'rof', definition: 'Rough, tough, harsh. Describes conditions or a person.', origin: 'Afrikaans', example: 'Die lewe is rof hieso' },
    { term: 'snotkop', definition: 'A young kid with a runny nose. Used affectionately or dismissively.', origin: 'Afrikaans', example: 'Toe hy nog ’n snotkop was' },
    { term: 'tackle', definition: 'To approach, to flirt with, or to deal with something.', origin: 'South African English', example: 'Hy het haar getackle by die jol' },
    { term: 'uitkyk', definition: 'Look out, be careful. A watchman or lookout.', origin: 'Afrikaans', example: 'Hy staan uitkyk op die hoek' },
    { term: 'vlam', definition: 'Flame. "Vlam vang" = to catch fire, to get angry or excited.', origin: 'Afrikaans', example: 'Die party vang vlam' },
    { term: 'wyn', definition: 'Wine. Cape wine culture is deeply embedded in Flats social life.', origin: 'Afrikaans', example: 'Hy drink goedkoop wyn' },
    { term: 'xhosa', definition: 'One of SA’s major languages. Many loanwords in SDK.', origin: 'Language reference', example: 'Hy praat bietjie Xhosa' },
    { term: 'yster-man', definition: 'A tough guy, an iron man. Someone with unbreakable resolve.', origin: 'Afrikaans', example: 'Hy is die yster-man van die wyk' },
    { term: 'zoef', definition: 'To move very fast. "Hy zoef verby" = he zooms past.', origin: 'Afrikaans onomatopoeia', example: 'Die kar zoef verby' },
    { term: 'aaand', definition: 'Extended "aand" (night) used to emphasize a long night.', origin: 'Kaaps phonetic', example: 'Dis ’n laaang aaand' },
    { term: 'boontoe', definition: 'Upwards, going up. "Hy gaan boontoe" = he’s going up (success).', origin: 'Afrikaans', example: 'Ons gaan net boontoe van hier' },
    { term: 'cloudy', definition: 'Confused, not thinking clearly. In a mental fog.', origin: 'Cape Flats slang', example: 'My kop is cloudy vandag' },
    { term: 'daai kant', definition: 'That side, over there. Points to a direction or area.', origin: 'Afrikaans', example: 'Hy bly daai kant' },
    { term: 'eerlik', definition: 'Honestly, truthfully. "Eerlik waar" = honestly truly.', origin: 'Afrikaans', example: 'Eerlik bra, ek het nie geweet nie' },
    { term: 'fliek', definition: 'Movies, cinema. "Na die fliek gaan" = go to the movies.', origin: 'Afrikaans from English "flick"', example: 'Ons gaan fliek toe' },
    { term: 'gesond', definition: 'Healthy. "Bly gesond" = stay healthy (farewell).', origin: 'Afrikaans', example: 'Bly gesond bra' },
    { term: 'heuningbos', definition: 'Honeybush — a Cape plant used for tea. Life metaphor for sweetness in hardship.', origin: 'Afrikaans agricultural', example: 'Soos heuningbos uit die veld' },
    { term: 'ingedraai', definition: 'Turned in, folded in. Also: asleep or withdrawn.', origin: 'Afrikaans', example: 'Hy is al ingedraai' },
    { term: 'jags', definition: 'Horny, lustful, sexually aroused.', origin: 'Afrikaans', example: 'Hy is jags vir haar' },
    { term: 'klippe', definition: 'Rocks, stones. "Oor die klippe loop" = walk over rough terrain.', origin: 'Afrikaans', example: 'Ons loop oor klippe om hier te kom' },
    { term: 'lelik', definition: 'Ugly, naughty, badly behaved. "Moenie lelik wees nie."', origin: 'Afrikaans', example: 'Moenie lelik wees nie' },
    { term: 'maklik', definition: 'Easy, simple. "Dis nie maklik nie" = it’s not easy.', origin: 'Afrikaans', example: 'Die lewe is nie maklik nie' },
    { term: 'naweek', definition: 'Weekend. "Die naweek" = this weekend.', origin: 'Afrikaans', example: 'Ons kuier die naweek' },
    { term: 'oorlog', definition: 'War. Used metaphorically for gang conflict or personal battles.', origin: 'Afrikaans', example: 'Dit is oorlog in die strate' },
    { term: 'plek', definition: 'Place, spot, location. "My plek" = my place.', origin: 'Afrikaans', example: 'Kom na my plek toe' },
    { term: 'reg', definition: 'Right, correct, okay. Also: fixed, sorted.', origin: 'Afrikaans', example: 'Alles is reg bra' },
    { term: 'saam', definition: 'Together. "Ons is saam" = we’re together.', origin: 'Afrikaans', example: 'Ons staan saam' },
    { term: 'tafel', definition: 'Table. Also referenced for Table Mountain.', origin: 'Afrikaans', example: 'Die Tafelberg staan bo die stad' },
    { term: 'vuil', definition: 'Dirty. Used literally and for playing dirty.', origin: 'Afrikaans', example: 'Hy speel vuil' },
    { term: 'wag', definition: 'Wait. "Wag hier" = wait here.', origin: 'Afrikaans', example: 'Wag vir my by die hoek' },
    { term: 'skaam', definition: 'Shy, ashamed, embarrassed.', origin: 'Afrikaans', example: 'Moenie skaam wees nie' },
    { term: 'dik', definition: 'Thick, fat. Also means "fed up" as in "dik vir jou."', origin: 'Afrikaans', example: 'Ek is dik vir jou stories' },
    { term: 'geld', definition: 'Money. The Afrikaans word for money.', origin: 'Afrikaans', example: 'Niks geld in die sak nie' },
    { term: 'harde', definition: 'Hard, tough. "Harde tye" = hard times.', origin: 'Afrikaans', example: 'Dis harde tye hier op die flats' },
    { term: 'iets', definition: 'Something. "Hy weet iets" = he knows something.', origin: 'Afrikaans', example: 'Daar is iets verkeerd' },
    { term: 'jong', definition: 'Young, also used as "man" in conversation filler.', origin: 'Afrikaans', example: 'Jong, wat maak jy?' },
    { term: 'koning', definition: 'King. "Die koning van die flats" = the king of the flats.', origin: 'Afrikaans', example: 'Hy dink hy is die koning' },
    { term: 'laaste', definition: 'Last, final. "Die laaste kans" = the last chance.', origin: 'Afrikaans', example: 'Dis jou laaste kans' },
    { term: 'mielies', definition: 'Corn/maize. Staple food in SA culture.', origin: 'Afrikaans from Portuguese', example: 'Ma kook mielies vir ons' },
    { term: 'nag', definition: 'Night. "In die nag" = at night, when things happen on the streets.', origin: 'Afrikaans', example: 'Die nag is lank en donker' },
    { term: 'ondertoe', definition: 'Downwards, going down. Opposite of "boontoe."', origin: 'Afrikaans', example: 'Hy gaan ondertoe' },
    { term: 'program', definition: 'A scheme, plan, or activity. "Wat is die program?" = what’s the plan?', origin: 'Cape Flats slang', example: 'Wat is die program vanaand?' },
    { term: 'rykman', definition: 'A rich person. Someone with money and status.', origin: 'Afrikaans', example: 'Hy speel rykman' },
    { term: 'swak', definition: 'Weak, poor quality, bad. "Swak move" = a bad move.', origin: 'Afrikaans', example: 'Daai was ’n swak move' },
    { term: 'toe', definition: 'Then, at that time. Also: closed/shut.', origin: 'Afrikaans', example: 'Toe hy daar aankom' },
    { term: 'umfaan', definition: 'A young man, a boy worker. Township term.', origin: 'Zulu/Xhosa', example: 'Die umfaan leer vinnig' },
    { term: 'vetkoek', definition: 'Deep-fried dough ball. Classic SA comfort food.', origin: 'Afrikaans', example: 'Ma se vetkoeke is die beste' },
    { term: 'wêreld', definition: 'World. "Teen die wêreld" = against the world.', origin: 'Afrikaans', example: 'Ons teen die wêreld' },
    { term: 'xaxa', definition: 'To mess around, play, or joke. Cape slang.', origin: 'Cape Flats slang', example: 'Moenie xaxa met my nie' },
    { term: 'ystervark', definition: 'Porcupine. Used as slang for someone who is prickly/defensive.', origin: 'Afrikaans', example: 'Hy is soos ’n ystervark' },
    { term: 'zig-zag', definition: 'To dodge, to evade. Describing erratic movement.', origin: 'English', example: 'Hy zig-zag deur die strate' },
    { term: 'blerrie', definition: 'Bloody. Common Afrikaans expletive/intensifier.', origin: 'Afrikaans from English', example: 'Daai blerrie ou' },
    { term: 'stront', definition: 'Manure, crap. Used as an expletive or to describe rubbish.', origin: 'Afrikaans', example: 'Hy praat stront' },
    { term: 'hoendervleis', definition: 'Goosebumps. Literally "chicken flesh." Used for intense music moments.', origin: 'Afrikaans', example: 'Daai verse gee my hoendervleis' },
    { term: 'kwela-kwela', definition: 'A police van. The vehicle that picks up suspects.', origin: 'Zulu "climb, climb"', example: 'Die kwela-kwela het hom gevat' },
    { term: 'skolliebol', definition: 'A rough kid, a thug in training. Not fully grown but already street.', origin: 'Cape Flats slang', example: 'Daai skolliebol ken die strate' },
    { term: 'stokvel', definition: 'A communal savings club. Members contribute monthly, rotating payouts.', origin: 'South African financial culture', example: 'Ma is in ’n stokvel' },
    { term: 'langarm', definition: 'A style of ballroom dancing popular in the Cape.', origin: 'Afrikaans dance culture', example: 'Hulle dans langarm op die Saterdag' },
    { term: 'smokkel', definition: 'To smuggle. Also used for sneaking around or secret dealings.', origin: 'Afrikaans', example: 'Hy smokkel goed in' },
    { term: 'stief', definition: 'Step- (as in stepfather/mother). Also used as an intensifier meaning very.', origin: 'Afrikaans', example: 'Dis stief lekker' },
    { term: 'swaai', definition: 'To swing, to wave. "Swaai jou goed" = swing your stuff (dance).', origin: 'Afrikaans', example: 'Swaai daai ding' },
    { term: 'toeka', definition: 'Long ago, in the old days. Nostalgic reference.', origin: 'Afrikaans', example: 'Van toeka af is dit so' },
    { term: 'vatjou', definition: 'Watch yourself, be careful. A warning.', origin: 'Cape Flats from "vat jou"', example: 'Vatjou bra, dis gevaarlik' },
    { term: 'woes', definition: 'Wild, fierce, aggressive. Describes chaotic events.', origin: 'Afrikaans', example: 'Die naand was woes' },
    { term: 'gaanstaan', definition: 'Go stand, go away. Dismissive instruction.', origin: 'Afrikaans', example: 'Gaanstaan daar anderkant' },
    { term: 'dikbek', definition: 'Sulky, pouty, in a bad mood. "Hy is dikbek" = he’s sulking.', origin: 'Afrikaans', example: 'Moenie so dikbek wees nie' },
    { term: 'grappie', definition: 'A joke, something funny. "Dis net ’n grappie" = it’s just a joke.', origin: 'Afrikaans diminutive', example: 'Dis maar net ’n grappie bra' },
    { term: 'kruip', definition: 'To crawl, to sneak. "Hy kruip weg" = he hides/sneaks away.', origin: 'Afrikaans', example: 'Moenie wegkruip nie' },
    { term: 'skrik', definition: 'To get a fright, to be scared. "Moenie skrik nie" = don’t be scared.', origin: 'Afrikaans', example: 'Hy het geskrik vir die boere' },
    { term: 'styf', definition: 'Stiff, tight, close together. Also "stingy."', origin: 'Afrikaans', example: 'Hy hou sy geld styf vas' },
    { term: 'sukkel', definition: 'To struggle, to have a hard time with something.', origin: 'Afrikaans', example: 'Ek sukkel met die lewe' },
    { term: 'totsiens', definition: 'Goodbye, farewell. Formal but commonly shortened.', origin: 'Afrikaans', example: 'Totsiens bra, bly safe' },
    { term: 'uitgefreak', definition: 'Freaked out, panicked, extremely anxious.', origin: 'Afrikaans/English hybrid', example: 'Hy is heeltemal uitgefreak' },
    { term: 'voluit', definition: 'Full out, at maximum. "Voluit gaan" = go all out.', origin: 'Afrikaans', example: 'Hy gaan voluit op die stage' },
    { term: 'wegjaag', definition: 'To chase away, to drive off.', origin: 'Afrikaans', example: 'Hulle het hom weggejaag' },
    { term: 'zat', definition: 'Drunk, intoxicated. Very common Cape Flats term.', origin: 'Afrikaans', example: 'Hy is zat soos ’n vis' },
    { term: 'skuld', definition: 'Debt, owing money. "In die skuld wees" = be in debt.', origin: 'Afrikaans', example: 'Hy sit in die skuld' },
    { term: 'spyt', definition: 'Regret, sorry. "Ek is spyt" = I regret it.', origin: 'Afrikaans', example: 'Dis te laat vir spyt' },
    { term: 'vlug', definition: 'To flee, escape. Running from danger or law.', origin: 'Afrikaans', example: 'Hy moes vlug van die scene' },
    { term: 'aanhou', definition: 'To continue, keep going, persist.', origin: 'Afrikaans', example: 'Hy hou aan grind' },
    { term: 'deurdruk', definition: 'To push through, to persevere despite obstacles.', origin: 'Afrikaans', example: 'Ons deurdruk elke dag' },
    { term: 'vashou', definition: 'Hold tight, hang on. Also: to keep something.', origin: 'Afrikaans', example: 'Hou vas bra, ons maak dit' },
    { term: 'terug', definition: 'Back, return. "Ek is terug" = I’m back.', origin: 'Afrikaans', example: 'Hy is terug op die block' },
    { term: 'oppad', definition: 'On the way. "Ek is oppad" = I’m on my way.', origin: 'Afrikaans', example: 'Ek is oppad bra' },
    { term: 'skoert', definition: 'To leave quickly, run away. Cape Flats version of "flee."', origin: 'Cape Flats slang', example: 'Ons moes skoert toe die boere kom' },
    { term: 'tune', definition: 'To tell, inform, or speak. "Hy tune my" = he tells me.', origin: 'South African English slang', example: 'Wat tune jy my?' },
    { term: 'gewoond', definition: 'Used to, accustomed. "Ek is gewoond" = I’m used to it.', origin: 'Afrikaans', example: 'Ek is gewoond aan die hustle' },
    { term: 'manier', definition: 'Way, method, manner. "Op die regte manier" = the right way.', origin: 'Afrikaans', example: 'Hy doen dit op sy manier' },
    { term: 'gesig', definition: 'Face. Also: facial features or reputation.', origin: 'Afrikaans', example: 'Sy gesig is bekend' },
    { term: 'stil', definition: 'Quiet, still, silent. "Bly stil" = keep quiet.', origin: 'Afrikaans', example: 'Hy bly stil oor alles' },
    { term: 'giemie', definition: 'A giggle or snicker. Low-key laughing at someone.', origin: 'Cape Flats slang', example: 'Moenie giemie nie' },
    { term: 'smous', definition: 'A street vendor or hawker. Someone who sells goods informally.', origin: 'Afrikaans from Yiddish', example: 'Die smous verkoop sy goed op die hoek' },
    { term: 'moesiekind', definition: 'A term of endearment for a cherished child or person close to you.', origin: 'Cape Malay Afrikaans', example: 'Daai laaitie is die moesiekind van die wyk' },
]


async function main() {
    console.log('🌱 Seeding KB with', SEED_TERMS.length, 'terms...')
    let added = 0

    for (const entry of SEED_TERMS) {
        await prisma.kBEntry.upsert({
            where: { term: entry.term },
            update: {
                definition: entry.definition,
                origin: entry.origin,
                example: entry.example,
            },
            create: {
                term: entry.term,
                definition: entry.definition,
                origin: entry.origin,
                example: entry.example,
                confidence: 0.9,
                isApproved: true,
            },
        })
        added++
    }

    console.log(`✅ KB seeded successfully! ${added} terms upserted.`)
    const total = await prisma.kBEntry.count({ where: { isApproved: true } })
    console.log(`📚 Total approved KB terms in DB: ${total}`)
}

main()
    .catch(e => { console.error(e); process.exit(1) })
    .finally(() => prisma.$disconnect())
